language: php

php:
  - "5.5"
  - "5.6"

branches:
  except:
    - development

before_script:
  - php -r "\$var = file_get_contents('config/config.yml-dist'); file_put_contents('config/config.yml', \$var);"
  - composer install --prefer-dist -o
  - php vendor/bin/phing
