language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

branches:
  except:
    - development

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist
  - cp config/config.yml-dist config/config.yml

script:
  - ./vendor/bin/phpunit