language: php

php:
  - "5.6"
  - "hhvm"
  - "nightly"

branches:
  except:
    - development

install:
  - composer self-update
  - composer update --prefer-dist

before_script:
  - cp config/config.yml-dist config/config.yml
  - composer dump-autoload

script:
  - phpunit
