# user route
user.home:
    path: /
    defaults: { _controller: 'User\Controller\User::get' }
    methods: [GET]

user.view:
    path: /{id}
    defaults: { _controller: 'User\Controller\User::view' }
    methods: [GET]
    requirements:
      id: \d+

user.update:
    path: /{id}
    defaults: { _controller: 'User\Controller\User::update' }
    methods: [PUT]
    requirements:
      id: \d+

user.delete:
    path: /{id}
    defaults: { _controller: 'User\Controller\User::delete' }
    methods: [DELETE]
    requirements:
      id: \d+

user.create:
    path: /
    defaults: { _controller: 'User\Controller\User::create' }
    methods: [POST]
