# event listeners
listeners:
  # User route events
  user.home.before  : \Skel\Event\User\Home\Before
  user.home.after   : \Skel\Event\User\Home\After
  user.home.finish  : \Skel\Event\User\Home\Finish
  user.create.before: \Skel\Event\User\Create\Before
  user.create.after : \Skel\Event\User\Create\After
  user.create.finish: \Skel\Event\User\Create\Finish
  user.update.before: \Skel\Event\User\Update\Before
  user.update.after : \Skel\Event\User\Update\After
  user.update.finish: \Skel\Event\User\Update\Finish
